/**
 * Generates the Elementor icon-library assets shipped inside each pack under
 * elementor/: a CSS file (one mask-image class per icon) and icons.json (the
 * `fetchJson` list Elementor's icon picker reads).
 *
 * Rendered markup by Elementor: <i class="ii-<slug> ii-<slug>-<name>"></i>
 * (displayPrefix + " " + prefix + name), so the base class carries the box
 * and the per-icon class carries the mask.
 */
import { gzipSync } from 'node:zlib';

/** Compact data-URI encoding for SVG (only characters that break url() are escaped). */
export function svgToDataUri( svg ) {
	const body = svg
		.replace( /"/g, "'" )
		.replace( /%/g, '%25' )
		.replace( /#/g, '%23' )
		.replace( /{/g, '%7B' )
		.replace( /}/g, '%7D' )
		.replace( /</g, '%3C' )
		.replace( />/g, '%3E' )
		.replace( /\s+/g, ' ' );
	return `data:image/svg+xml,${ body }`;
}

export function buildElementorAssets( pack, icons ) {
	const base = `ii-${ pack.slug }`;
	let css = `/* ${ pack.label } — generated by infinite-icons-packs. Icons: ${ pack.license.spdx }. */\n`;
	css += `.${ base }{display:inline-block;width:1em;height:1em;vertical-align:-.125em;background-color:currentColor;-webkit-mask-repeat:no-repeat;mask-repeat:no-repeat;-webkit-mask-position:center;mask-position:center;-webkit-mask-size:contain;mask-size:contain}\n`;
	for ( const icon of icons ) {
		const uri = svgToDataUri( icon.svg );
		css += `.${ base }-${ icon.name }{-webkit-mask-image:url("${ uri }");mask-image:url("${ uri }")}\n`;
	}
	const json = JSON.stringify( { icons: icons.map( ( i ) => i.name ) } );
	return {
		css,
		json,
		sizes: {
			css: Buffer.byteLength( css ),
			cssGzip: gzipSync( css ).length,
			json: Buffer.byteLength( json ),
		},
	};
}
