/**
 * manifest.json / LICENSE / ATTRIBUTION.md generation and schema validation.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import Ajv from 'ajv';
import addFormats from 'ajv-formats';
import { ROOT, REQUIRES_PLUGIN } from '../packs.config.mjs';

const schema = JSON.parse( readFileSync( path.join( ROOT, 'schemas', 'manifest.schema.json' ), 'utf8' ) );
const ajv = new Ajv( { allErrors: true, strict: true } );
addFormats( ajv );
const validate = ajv.compile( schema );

/**
 * @param {object} pack     Pack definition (with resolved upstream.version).
 * @param {string} version  Pack version, e.g. "1.42.0+ii.1".
 * @param {Array<{name:string,label:string,variant:string,keywords:string[],file:string}>} icons
 */
export function buildManifest( pack, version, icons ) {
	return {
		schema: 1,
		slug: pack.slug,
		label: pack.label,
		description: pack.description,
		version,
		upstream: { name: pack.upstream.name, version: pack.upstream.version, url: pack.upstream.url },
		license: { spdx: pack.license.spdx, attribution: pack.license.attribution },
		requires_plugin: REQUIRES_PLUGIN,
		variants: pack.variants.map( ( v ) => ( v.default ? { key: v.key, label: v.label, default: true } : { key: v.key, label: v.label } ) ),
		icons: icons.map( ( i ) => ( { name: i.name, label: i.label, variant: i.variant, keywords: i.keywords, file: i.file } ) ),
	};
}

/** @return {string[]} Human-readable schema errors (empty when valid). */
export function validateManifest( manifest ) {
	if ( validate( manifest ) ) return [];
	return ( validate.errors ?? [] ).map( ( e ) => `${ e.instancePath || '/' } ${ e.message }` );
}

export function writeAttribution( dir, pack, version ) {
	const md = `# ${ pack.label }

- Upstream: [${ pack.upstream.name } ${ pack.upstream.version }](${ pack.upstream.url })
- License: ${ pack.license.spdx } (see LICENSE)
- ${ pack.license.attribution }

This pack (${ version }) was generated by the
[Infinite Icons pipeline](https://github.com/CoderAbhinav/infinite-icons-packs) for the
Infinite Icons WordPress plugin. Icons were converted to fill-based single-path SVGs so
they survive WordPress core's icon sanitizer; no other changes were made.
`;
	writeFileSync( path.join( dir, 'ATTRIBUTION.md' ), md );
}

export function fallbackLicenseText( pack ) {
	return `${ pack.license.spdx }\n\n${ pack.license.attribution }\n\nSee ${ pack.upstream.url } for the full license text.\n`;
}
